language: ruby

script: bundle exec rspec

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

gemfile:
  - spec/gemfiles/rails-3.1.gemfile
  - spec/gemfiles/rails-3.2.gemfile
  - spec/gemfiles/rails-4.0.gemfile
  - spec/gemfiles/rails-4.1.gemfile
  - spec/gemfiles/rails-4.2.gemfile
  - spec/gemfiles/rails-edge.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-4.0.gemfile
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-4.1.gemfile
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-4.2.gemfile
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-edge.gemfile
